const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const State={MENU:'MENU',LOBBY:'LOBBY',CHAR:'CHARACTER_SELECT',BATTLE:'BATTLE',RESULT:'RESULT'};
let game={state:State.MENU,mode:'bot',playerLevel:1,story:{level:1,stage:1},selected:[],loadouts:{},activeUnitId:null,turn:'player',dice:null,path:[],phase:'select',units:[],blocked:new Set(),log:[],lobbyCode:null};
const chars=[
{id:'knight',name:'Iron Knight',role:'Fighter',unlock:1,hp:12,atk:2,skills:[['slash','Power Slash','active','Deal +1 attack damage.'],['guard','Stone Guard','active','Block: reduce next damage by 2.'],['armor','Iron Skin','passive','Take -1 damage from attacks.'],['taunt','Taunt','active','Enemy bot prefers this unit next turn.'],['counter','Counter Edge','passive','Deal 1 return damage after block.'],['charge','Shield Charge','active','Attack then push target 1 tile if possible.']]},
{id:'mage',name:'Blue Mage',role:'Mage',unlock:1,hp:9,atk:2,skills:[['bolt','Arc Bolt','active','Ranged attack up to 2 straight tiles.'],['heal','Mend','active','Heal ally for 3 anywhere.'],['focus','Arcane Focus','passive','Heal +1.'],['spark','Chain Spark','active','Deal 1 damage to nearby second enemy.'],['ward','Soft Ward','passive','First incoming hit each battle -1 damage.'],['renew','Renew','active','Heal 2 and cleanse block penalty.']]},
{id:'ranger',name:'Red Ranger',role:'Archer',unlock:10,hp:10,atk:2,skills:[['shot','Straight Shot','active','Attack up to 3 straight tiles.'],['trap','Pin Trap','active','Target loses 1 movement next turn.'],['eagle','Eagle Eye','passive','Range +1 on straight attacks.'],['rapid','Rapid Shot','active','Two weak shots for 1 damage each.'],['evade','Light Step','passive','First hit has 25% miss chance.'],['mark','Mark Target','active','Target takes +1 damage this round.']]},
{id:'cleric',name:'Sun Cleric',role:'Mage',unlock:20,hp:10,atk:1,skills:[['smite','Smite','active','Ranged holy hit for 2.'],['prayer','Prayer','active','Heal ally for 4.'],['blessing','Blessing','passive','Ally heals receive +1.'],['shield','Holy Shield','active','Give ally -2 damage shield.'],['aura','Calm Aura','passive','End turn heals self 1 if damaged.'],['revive','Last Light','active','Once per battle revive ally at 3 HP.']]}
];
function show(id){$$('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active')}
function setState(s){game.state=s;show(s===State.MENU?'#menuScreen':s===State.LOBBY?'#lobbyScreen':s===State.CHAR?'#characterScreen':s===State.BATTLE?'#battleScreen':'#resultScreen')}
function log(t){game.log.unshift(t);renderLog()}
function renderLog(){if(!$('#gameLog'))return;$('#gameLog').innerHTML=game.log.map(x=>`<div class="logLine">${x}</div>`).join('')}
$$('[data-action]').forEach(b=>b.onclick=()=>{let a=b.dataset.action;if(a==='story')startChar('story');if(a==='bot')startChar('bot');if(a==='create')createLobby();if(a==='join')joinLobby()});
$('#backMenuBtn').onclick=()=>setState(State.MENU);$('#lobbyBotBtn').onclick=()=>startChar('bot');$('#simulateJoinBtn').onclick=()=>{game.mode='pvp';$('#lobbyStatus').textContent='Opponent joined. Moving to character selection...';setTimeout(()=>startChar('pvp'),500)};
$('#charBackBtn').onclick=()=>setState(State.MENU);$('#startBattleBtn').onclick=()=>startBattle();$('#rollBtn').onclick=rollDice;$('#endTurnBtn').onclick=endTurn;$('#returnLobbyBtn').onclick=()=>confirm('Exit battle?')&&setState(State.MENU);$('#resultMenuBtn').onclick=()=>setState(State.MENU);$('#nextBtn').onclick=()=>{if(game.mode==='story')startChar('story');else startChar(game.mode)};
function createLobby(){game.lobbyCode=Math.random().toString(36).substring(2,7).toUpperCase();$('#lobbyCode').textContent=game.lobbyCode;$('#lobbyStatus').textContent='Waiting for opponent...';setState(State.LOBBY)}
function joinLobby(){let code=$('#joinCodeInput').value.trim().toUpperCase();if(code.length<3)return alert('Enter a game code.');game.lobbyCode=code;$('#lobbyCode').textContent=code;$('#lobbyStatus').textContent='Joined lobby. Simulating host connection...';setState(State.LOBBY);setTimeout(()=>startChar('pvp'),700)}
function startChar(mode){game.mode=mode;game.selected=[];game.loadouts={};$('#charModeTitle').textContent=mode==='story'?`Story Mode: Level ${game.story.level}-${game.story.stage}`:mode==='pvp'?'PvP Character Selection':'Bot Battle Character Selection';renderChars();setState(State.CHAR)}
function renderChars(){const wrap=$('#characterList');wrap.innerHTML='';chars.forEach(c=>{let locked=game.playerLevel<c.unlock, sel=game.selected.includes(c.id);let d=document.createElement('div');d.className=`charCard ${sel?'selected':''} ${locked?'locked':''}`;d.innerHTML=`<h3>${c.name}</h3><p>${c.role}</p><p>${locked?'Unlock at player level '+c.unlock:'Unlocked'}</p>`;d.onclick=()=>{if(locked)return;if(sel)game.selected=game.selected.filter(x=>x!==c.id);else if(game.selected.length<2){game.selected.push(c.id);defaultLoadout(c)}renderChars();renderSkills(c.id)};wrap.appendChild(d)});$('#selectedSummary').textContent=`Selected: ${game.selected.length} / 2`;$('#startBattleBtn').disabled=game.selected.length!==2}
function defaultLoadout(c){if(game.loadouts[c.id])return;let active=c.skills.filter(s=>s[2]==='active').slice(0,2).map(s=>s[0]);let passive=c.skills.find(s=>s[2]==='passive')[0];game.loadouts[c.id]=[...active,passive]}
function renderSkills(id){let c=chars.find(x=>x.id===id);if(!c)return;defaultLoadout(c);$('#skillPanel h3').textContent=c.name+' Skills';$('#skillContent').innerHTML=`<div class="skillGrid">${c.skills.map((s,i)=>{let unlocked=i<3||i===3||i===4||i===5;let eq=game.loadouts[c.id].includes(s[0]);return `<div class="skillCard ${eq?'equipped':''}"><b>${s[1]}</b> <small>${s[2]}</small><p>${s[3]}</p><small>${unlocked?'Unlocked':'Locked'}</small></div>`}).join('')}</div>`}
function startBattle(){game.units=[];game.blocked=new Set(['2,2','3,2','5,3','1,5','6,5','4,6']);let picks=game.selected.map(id=>chars.find(c=>c.id===id));picks.forEach((c,i)=>game.units.push(makeUnit(c,'player',0,i?2:5)));let enemies=game.mode==='story'&&game.story.stage===3?[chars[0],chars[1],chars[2]]:[chars[0],chars[1]];enemies.forEach((c,i)=>game.units.push(makeUnit(c,'enemy',7,i?2:5,i===2)));game.turn='player';game.phase='select';game.dice=null;game.path=[];game.activeUnitId=null;game.log=[];$('#modeLabel').textContent=game.mode.toUpperCase();$('#storyLabel').textContent=game.mode==='story'?`Level ${game.story.level} Stage ${game.story.stage}`:'';setState(State.BATTLE);renderBoard();log('Select a player unit, then roll dice.')}
function makeUnit(c,team,x,y,boss=false){return{id:team+'_'+c.id+'_'+Math.random().toString(36).slice(2,5),char:c,team,x,y,hp:c.hp+(boss?4:0),maxHp:c.hp+(boss?4:0),atk:c.atk+(boss?1:0),block:false,acted:false,taunt:false}}
function renderBoard(){const b=$('#board');b.innerHTML='';for(let y=0;y<8;y++)for(let x=0;x<8;x++){let t=document.createElement('div');t.className=`tile ${(x+y)%2?'dark':''} ${game.blocked.has(`${x},${y}`)?'blocked':''}`;t.dataset.x=x;t.dataset.y=y;t.textContent=`${x},${y}`;if(isValidNext(x,y))t.classList.add('valid');if(game.path.some(p=>p.x===x&&p.y===y))t.classList.add('path');t.onclick=()=>tileClick(x,y);let u=game.units.find(u=>u.x===x&&u.y===y&&u.hp>0);if(u){let el=document.createElement('div');el.className=`unit ${u.team} ${u.id===game.activeUnitId?'active':''}`;el.innerHTML=`${u.char.role[0]}<span class="hpTag">${u.hp}</span>`;t.appendChild(el)}b.appendChild(t)}renderStatus();renderLog();$('#turnLabel').textContent=game.turn==='player'?'Player Turn':'Enemy Turn';$('#diceBox').textContent=game.dice??'-'}
function renderStatus(){$('#unitStatus').innerHTML=game.units.map(u=>`<div class="statusUnit"><b>${u.team==='player'?'Blue':'Red'} ${u.char.name}</b><br>HP ${u.hp}/${u.maxHp} ${u.hp<=0?'DOWN':''}</div>`).join('')}
function current(){return game.units.find(u=>u.id===game.activeUnitId)}
function tileClick(x,y){if(game.turn!=='player')return;let u=game.units.find(u=>u.x===x&&u.y===y&&u.team==='player'&&u.hp>0&&!u.acted);if(game.phase==='select'&&u){game.activeUnitId=u.id;game.phase='roll';log(`${u.char.name} selected. Roll dice.`);renderBoard();return}if(game.phase==='move'){let a=current();if(!a)return;let last=game.path.at(-1)||{x:a.x,y:a.y};if(Math.abs(last.x-x)+Math.abs(last.y-y)!==1)return log('Invalid tile: move orthogonally only.');if(game.blocked.has(`${x},${y}`)||unitAt(x,y))return log('Invalid tile: blocked or occupied.');game.path.push({x,y});renderBoard();if(game.path.length===game.dice)setTimeout(resolveMove,250)}}
function isValidNext(x,y){if(game.phase!=='move')return false;let a=current();if(!a)return false;let last=game.path.at(-1)||{x:a.x,y:a.y};return Math.abs(last.x-x)+Math.abs(last.y-y)===1&&!game.blocked.has(`${x},${y}`)&&!unitAt(x,y)}
function unitAt(x,y){return game.units.find(u=>u.x===x&&u.y===y&&u.hp>0)}
function rollDice(){if(game.turn!=='player'||game.phase!=='roll')return log('Select an unused character first.');let box=$('#diceBox');box.classList.add('rolling');let n=0,spin=setInterval(()=>{box.textContent=1+Math.floor(Math.random()*6);n++},70);setTimeout(()=>{clearInterval(spin);box.classList.remove('rolling');game.dice=1+Math.floor(Math.random()*6);box.textContent=game.dice;game.phase='move';game.path=[];log(`Rolled ${game.dice}. Move exactly ${game.dice} steps.`);renderBoard()},650)}
function resolveMove(){let a=current();let dest=game.path.at(-1);a.x=dest.x;a.y=dest.y;game.path=[];game.phase='action';renderBoard();let targets=adjacentEnemies(a);if(targets.length)showActions(a,targets);else{log('No valid target on final tile. Action skipped.');a.acted=true;game.phase='select';checkTurnDone();renderBoard()}}
function adjacentEnemies(a){return game.units.filter(u=>u.team!==a.team&&u.hp>0&&Math.abs(u.x-a.x)+Math.abs(u.y-a.y)===1)}
function showActions(a,targets){let p=$('#actionPanel');p.innerHTML='';p.classList.remove('hidden');let atk=document.createElement('button');atk.textContent='Attack';atk.onclick=()=>doAttack(a,targets[0]);p.appendChild(atk);if(a.char.role==='Fighter'){let bl=document.createElement('button');bl.textContent='Block';bl.onclick=()=>{p.classList.add('hidden');setTimeout(()=>{a.block=true;a.acted=true;log(`${a.char.name} blocks.`);game.phase='select';checkTurnDone();renderBoard()},350)};p.appendChild(bl)}if(a.char.role==='Mage'){let heal=document.createElement('button');heal.textContent='Heal';heal.onclick=()=>doHeal(a);p.appendChild(heal)}let skip=document.createElement('button');skip.textContent='Skip';skip.onclick=()=>{p.classList.add('hidden');a.acted=true;game.phase='select';checkTurnDone();renderBoard()};p.appendChild(skip)}
function doAttack(a,t){$('#actionPanel').classList.add('hidden');setTimeout(()=>{let dmg=a.atk+(game.loadouts[a.char.id]?.includes('slash')?1:0);if(t.block){dmg=Math.max(0,dmg-2);t.block=false}if(game.loadouts[t.char.id]?.includes('armor'))dmg=Math.max(0,dmg-1);t.hp=Math.max(0,t.hp-dmg);log(`${a.char.name} hits ${t.char.name} for ${dmg}.`);a.acted=true;afterAction()},450)}
function doHeal(a){let allies=game.units.filter(u=>u.team===a.team&&u.hp>0&&u.hp<u.maxHp);if(!allies.length)return log('No ally needs healing.');let target=allies[0], amt=3+(game.loadouts[a.char.id]?.includes('focus')?1:0);$('#actionPanel').classList.add('hidden');setTimeout(()=>{target.hp=Math.min(target.maxHp,target.hp+amt);log(`${a.char.name} heals ${target.char.name} for ${amt}.`);a.acted=true;afterAction()},450)}
function afterAction(){if(checkWinLose())return;game.phase='select';checkTurnDone();renderBoard()}
function checkTurnDone(){if(game.units.filter(u=>u.team==='player'&&u.hp>0).every(u=>u.acted))endTurn()}
function endTurn(){if(game.turn==='player'){game.units.filter(u=>u.team==='player').forEach(u=>u.acted=false);game.turn='enemy';game.phase='enemy';$('#actionPanel').classList.add('hidden');renderBoard();setTimeout(enemyTurn,600)}else{game.units.filter(u=>u.team==='enemy').forEach(u=>u.acted=false);game.turn='player';game.phase='select';game.dice=null;log('Player turn. Select a unit.');renderBoard()}}
async function enemyTurn(){for(const e of game.units.filter(u=>u.team==='enemy'&&u.hp>0)){let d=1+Math.floor(Math.random()*6);let target=nearestPlayer(e);if(!target)break;for(let i=0;i<d;i++){let opts=[[1,0],[-1,0],[0,1],[0,-1]].map(([dx,dy])=>({x:e.x+dx,y:e.y+dy})).filter(p=>p.x>=0&&p.y>=0&&p.x<8&&p.y<8&&!game.blocked.has(`${p.x},${p.y}`)&&!unitAt(p.x,p.y));opts.sort((a,b)=>Math.abs(a.x-target.x)+Math.abs(a.y-target.y)-Math.abs(b.x-target.x)-Math.abs(b.y-target.y));if(opts[0]&&Math.abs(e.x-target.x)+Math.abs(e.y-target.y)>1){e.x=opts[0].x;e.y=opts[0].y;renderBoard();await wait(180)}}let adj=adjacentEnemies(e)[0];if(adj){let dmg=e.atk;if(adj.block){dmg=Math.max(0,dmg-2);adj.block=false}if(game.loadouts[adj.char.id]?.includes('armor'))dmg=Math.max(0,dmg-1);adj.hp=Math.max(0,adj.hp-dmg);log(`${e.char.name} attacks ${adj.char.name} for ${dmg}.`);renderBoard();await wait(350)}if(checkWinLose())return}endTurn()}
function nearestPlayer(e){return game.units.filter(u=>u.team==='player'&&u.hp>0).sort((a,b)=>Math.abs(a.x-e.x)+Math.abs(a.y-e.y)-Math.abs(b.x-e.x)-Math.abs(b.y-e.y))[0]}
function wait(ms){return new Promise(r=>setTimeout(r,ms))}
function checkWinLose(){let players=game.units.some(u=>u.team==='player'&&u.hp>0), enemies=game.units.some(u=>u.team==='enemy'&&u.hp>0);if(players&&enemies)return false;let win=players&&!enemies;if(game.mode==='story'){if(win){game.story.stage++;if(game.story.stage>3){game.story.stage=1;game.story.level++;game.playerLevel++;}}else game.story.stage=1;}$('#resultTitle').textContent=win?'Victory':'Defeat';$('#resultText').textContent=win?xpText(true):xpText(false);setState(State.RESULT);return true}
function xpText(win){return `${win?'You won':'You lost'}. Used characters gained EXP placeholder. ${game.mode==='story'?`Story progress: Level ${game.story.level}, Stage ${game.story.stage}.`:''}`}
setState(State.MENU);
